# -*- coding: utf-8 -*-
# SPDX-License-Identifier: MIT
"""Is the hole-generator target count = the geometry's FIRST BETTI NUMBER?

THE STALL.  The greedy tree-cotree collapse in equiterminal._hole_cycles
declares one generator per matching stall and admits in its own
docstring that this "can in principle leave more generators than the
true deficit".  At 200 nm the JTL declares 294 hole generators; the
macro Schur block is rank-deficient by 2, so only 292 are independent.
Those 2 dependent columns are what the LU inverts into v-cycle noise.

A dedup needs a TARGET it can trust.  The docket's candidate is "one
generator per moat", i.e. the target is the first Betti number of the
conductor -- the number of independent tunnels through it.

b1 is computable with pure integer arithmetic, no solver, no linear
algebra, from the Euler characteristic of the cubical complex the
occupied voxels generate:

    chi = V - E + F - C          (cells of the cubical complex)
    chi = b0 - b1 + b2
    =>  b1 = b0 + b2 - chi

b0 = connected components of the conductor, b2 = enclosed cavities.
V/E/F/C are counted by logical-or over neighbour shifts.

PREDICTION UNDER TEST:  b1 == 292 for the 200 nm JTL.
If it holds, every scale gets its exact generator target for free.

Costs seconds.  No tree build, no prepare, no solve -- deliberately.
"""
import os
import sys

sys.path[:0] = ['src', 'studies']

import numpy as np

TOML = os.environ.get(
    'TOML', '/home/tims/.claude/jobs/165528bd/tmp/rsfq/jtl_A_200e-9.toml')


def cubical_counts(occ):
    """(V, E, F, C) of the cubical complex generated by occupied voxels."""
    occ = np.ascontiguousarray(occ.astype(bool))
    C = int(occ.sum())

    def anyshift(offsets):
        """occupied-voxel indicator OR'd over the given corner offsets."""
        nx, ny, nz = occ.shape
        acc = np.zeros((nx + 1, ny + 1, nz + 1), dtype=bool)
        for dx, dy, dz in offsets:
            acc[dx:dx + nx, dy:dy + ny, dz:dz + nz] |= occ
        return int(acc.sum())

    # a vertex of the complex exists if ANY of the 8 voxels meeting it
    # is occupied
    V = anyshift([(dx, dy, dz) for dx in (0, 1)
                  for dy in (0, 1) for dz in (0, 1)])
    # an edge along axis a exists if any of the 4 voxels around it is
    # occupied; the edge lattice is full in a and vertex-like elsewhere
    E = 0
    for a in range(3):
        offs = []
        for d0 in (0, 1):
            for d1 in (0, 1):
                o = [0, 0, 0]
                o[(a + 1) % 3] = d0
                o[(a + 2) % 3] = d1
                offs.append(tuple(o))
        nx, ny, nz = occ.shape
        shape = [nx + 1, ny + 1, nz + 1]
        shape[a] = occ.shape[a]
        acc = np.zeros(shape, dtype=bool)
        for dx, dy, dz in offs:
            acc[dx:dx + nx, dy:dy + ny, dz:dz + nz] |= occ
        E += int(acc.sum())
    # a face perpendicular to axis a exists if either voxel touching it
    # is occupied
    F = 0
    for a in range(3):
        nx, ny, nz = occ.shape
        shape = [nx, ny, nz]
        shape[a] = occ.shape[a] + 1
        acc = np.zeros(shape, dtype=bool)
        o0 = [0, 0, 0]
        o1 = [0, 0, 0]
        o1[a] = 1
        for dx, dy, dz in (tuple(o0), tuple(o1)):
            acc[dx:dx + nx, dy:dy + ny, dz:dz + nz] |= occ
        F += int(acc.sum())
    return V, E, F, C


def main():
    import sppeec_input
    print('loading %s' % TOML)
    prob = sppeec_input.load(TOML)
    m = prob.model()
    # the JTL is niobium: sigma == 0 and occupancy lives in lambdaL, so
    # struc() (which ORs both) is the only correct occupancy source
    occ = np.asarray(m.struc()) != 0
    print('grid %s, conductor voxels %d  (sigma!=0: %d, lambdaL!=0: %d)'
          % ('x'.join(str(d) for d in occ.shape), int(occ.sum()),
             int((np.asarray(m.sigma) != 0.0).sum()),
             0 if m.lambdaL is None
             else int((np.asarray(m.lambdaL) != 0.0).sum())))

    V, E, F, C = cubical_counts(occ)
    chi = V - E + F - C
    print('\ncubical complex:  V %d  E %d  F %d  C %d' % (V, E, F, C))
    print('Euler characteristic chi = %d' % chi)

    from scipy import ndimage
    # the cubical complex connects voxels that share ANY vertex
    lab26, b0_26 = ndimage.label(occ, structure=np.ones((3, 3, 3)))
    st6 = ndimage.generate_binary_structure(3, 1)
    lab6, b0_6 = ndimage.label(occ, structure=st6)
    print('components: 26-conn %d, 6-conn %d' % (b0_26, b0_6))

    # cavities: background components that do NOT touch the padded border
    bg = ~occ
    bgp = np.pad(bg, 1, constant_values=True)
    labb, nb = ndimage.label(bgp, structure=st6)
    outer = labb[0, 0, 0]
    cav = nb - 1 if outer else nb
    touching = set(np.unique(np.concatenate([
        labb[0].ravel(), labb[-1].ravel(),
        labb[:, 0].ravel(), labb[:, -1].ravel(),
        labb[:, :, 0].ravel(), labb[:, :, -1].ravel()])))
    touching.discard(0)
    cav = nb - len(touching)
    print('background components %d, border-touching %d => cavities %d'
          % (nb, len(touching), cav))

    for name, b0 in (('26-conn', b0_26), ('6-conn', b0_6)):
        b1 = b0 + cav - chi
        print('\nb0 (%s) = %d, b2 = %d  =>  b1 = %d' % (name, b0, cav, b1))

    print('\n--- comparison ---')
    print('greedy collapse declared      294 hole generators (200 nm log)')
    print('independent (macro rank)      292')
    print('b1 above is the prediction; 292 is the target.')


if __name__ == '__main__':
    main()
